name: Get Workflow RUN URL with run_id and job_id

on:
  workflow_dispatch:

jobs:
  get-run-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Configure git for private modules
        run:
          echo "machine github.com login x password ${{ secrets.GIT_HUB_TOKEN }}" > ~/.netrc
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 #install the python needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Get Job ID
        id: get_job_id
        run: |
          job_id=$(curl -s -H "Authorization: token ${{ secrets.GIT_HUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs" \
            | jq -r '.jobs[] | select(.name == "${{ github.job }}") | .id')
          echo "::set-output name=job_id::$job_id"
          echo "REPO_NAME=${{ github.repository }}" >> $GITHUB_ENV
          echo "JOB_ID=${job_id}" >> $GITHUB_ENV
          echo "RUN_ID=${{ github.run_id }}" >> $GITHUB_ENV
      - name: Print Workflow URL
        run: |
          echo "job_id: ${{ steps.get_job_id.outputs.job_id }}"
          echo "Workflow URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ steps.get_job_id.outputs.job_id }}"
      - name: Run Python Script
        run: |
          python access_control/logic.py
        env:
          REPO_NAME: ${{ github.repository }}
          RUN_ID: ${{ env.RUN_ID }}
          JOB_ID: ${{ env.JOB_ID }}
          